t_DUCT = 0.01;                       %Duct thickness, meters
T_mi = 20;                  %mean inlet temperature, degC 
%T_me = 30;                  %maximum mean duct exit temperature, degC
c_p = 1007;                          %Specific heat of air between 15 and 70 deg C, J/(kg*K) FROM TABLE
k_duct = 392                             %thermal conductivity, CHOSEN MATERIAL @T_bulk??
k_air = 0.02625                      %W/(m*K), based on a temperature of T_bulk, FROM TABLE
A_c_walls = L_DUCT * L_SIDE * 4;          %Cross sectional area of duct side for conduction, m^2 IGNORES CORNER AREA
A_c_CPUs = 0.0014 * N_CPU;               %total cross sectional area of CPUs for contact resistance, m^2
h_c = 30000 %thermal paste thermal contact coefficient, W/(m^2*K) PICK AN ACTUAL PASTE
rho = 1.145;                         %kg/m^3, based on a temperature of T_bulk, FROM TABLE
nu = 1.655e-5;                       %m^2/s assumed based on a temperature of T_bulk, FROM TABLE
Pr = 0.7268;                         %Prandtl number, assumed based on a temperature of T_bulk, FROM TABLE